# Generated by Django 3.2.8 on 2022-09-09 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('coin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='company',
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('1', 'طيران'), ('2', 'بري'), ('3', 'بحري'), ('4', 'تكسي'), ('5', 'شحن'), ('6', 'فيزا'), ('7', 'تامين صحي'), ('8', 'سمة دخول'), ('9', 'شهادة صحية)')], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='package_suplaier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('memo', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.coin')),
                ('package_COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('package_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
