# Generated by Django 3.2.8 on 2022-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, choices=[('متاجرة', (('1', 'التأشيرات'), ('2', 'تذاكر طيران'), ('3', 'تذاكر برية'), ('4', 'تذاكر بحرية'), ('5', 'شحن'), ('6', 'حجز فندقي'), ('7', 'مستندات سفر'), ('8', 'عمولات'), ('9', 'تحويل عملة'), ('10', 'الاصول'), ('11', 'أرباح وخسائر'), ('12', 'رصيد مدور'), ('13', 'الاهتلاك'), ('14', 'مستحقات الموظفين'), ('15', 'التأمينات الاجتماعية'), ('16', 'المصروفات'))), ('الشركات و الزبائن', (('20', 'الزبائن'), ('21', 'شركات التأشيرات'), ('22', 'شركات نقل جوي'), ('23', 'شركات نقل بري'), ('24', 'شركات نقل بحري'), ('25', 'فنادق'), ('26', 'شركات شحن'), ('27', 'شركات تأمين صحي'))), ('حسابات الشركة', (('30', 'المالكين'), ('31', 'الموظفين'), ('32', 'الصناديق'), ('33', 'مصاريف يومية'), ('34', 'الحافلات')))], max_length=4)),
            ],
        ),
    ]
