# Generated by Django 3.2.8 on 2022-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
