# Generated by Django 3.2.8 on 2022-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
