# Generated by Django 3.2.8 on 2022-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0008_alter_account_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'company')},
        ),
    ]
