# Generated by Django 3.2.8 on 2022-07-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_cridt', models.CharField(choices=[('1', 'التأشيرات'), ('2', 'تذاكر طيران'), ('3', 'تذاكر برية'), ('4', 'تذاكر بحرية'), ('5', 'شحن'), ('6', 'حجز فندقي'), ('7', 'مستندات سفر'), ('8', 'مستحقات موظفين'), ('9', 'عمولات'), ('10', 'تحويل عملة'), ('11', 'الاصول'), ('12', 'أرباح وخسائر'), ('13', 'رصيد بداية المدة'), ('14', 'رصيد مدور'), ('15', 'المالكين'), ('16', 'الزبائن'), ('17', 'شركات التأشيرات'), ('18', 'شركات نقل جوي'), ('19', 'شركات نقل بري'), ('20', 'شركات نقل بحري'), ('21', 'فنادق'), ('22', 'شركات شحن'), ('23', 'شركات تأمين'), ('24', 'رواتب موظفين'), ('25', 'تأمينات اجتماعية'), ('26', 'الصناديق'), ('27', 'مصروفات'), ('28', 'الحافلات')], max_length=4)),
                ('sub_account_cridt', models.CharField(blank=True, choices=[('1', ''), ('2', ''), ('3', ''), ('4', ''), ('5', ''), ('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', 'Owner'), ('16', 'Customer'), ('17', 'Customer'), ('18', 'Customer'), ('19', 'Customer'), ('20', 'Customer'), ('21', 'Customer'), ('22', 'Customer'), ('23', 'Customer'), ('24', 'employee'), ('25', 'employee'), ('26', 'boxes'), ('27', 'Expenses'), ('28', 'bus')], max_length=4, null=True)),
                ('account_dept', models.CharField(choices=[('1', 'التأشيرات'), ('2', 'تذاكر طيران'), ('3', 'تذاكر برية'), ('4', 'تذاكر بحرية'), ('5', 'شحن'), ('6', 'حجز فندقي'), ('7', 'مستندات سفر'), ('8', 'مستحقات موظفين'), ('9', 'عمولات'), ('10', 'تحويل عملة'), ('11', 'الاصول'), ('12', 'أرباح وخسائر'), ('13', 'رصيد بداية المدة'), ('14', 'رصيد مدور'), ('15', 'المالكين'), ('16', 'الزبائن'), ('17', 'شركات التأشيرات'), ('18', 'شركات نقل جوي'), ('19', 'شركات نقل بري'), ('20', 'شركات نقل بحري'), ('21', 'فنادق'), ('22', 'شركات شحن'), ('23', 'شركات تأمين'), ('24', 'رواتب موظفين'), ('25', 'تأمينات اجتماعية'), ('26', 'الصناديق'), ('27', 'مصروفات'), ('28', 'الحافلات')], max_length=4)),
                ('sub_account_dept', models.CharField(blank=True, choices=[('1', ''), ('2', ''), ('3', ''), ('4', ''), ('5', ''), ('6', ''), ('7', ''), ('8', ''), ('9', ''), ('10', ''), ('11', ''), ('12', ''), ('13', ''), ('14', ''), ('15', 'Owner'), ('16', 'Customer'), ('17', 'Customer'), ('18', 'Customer'), ('19', 'Customer'), ('20', 'Customer'), ('21', 'Customer'), ('22', 'Customer'), ('23', 'Customer'), ('24', 'employee'), ('25', 'employee'), ('26', 'boxes'), ('27', 'Expenses'), ('28', 'bus')], max_length=4, null=True)),
                ('ked_date', models.DateTimeField(auto_now_add=True)),
                ('dept', models.PositiveIntegerField(default=0)),
                ('cridt', models.PositiveIntegerField(default=0)),
                ('memo', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
