# Generated by Django 3.2.8 on 2022-07-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ked', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ked.journal'),
        ),
    ]
