# Generated by Django 3.2.8 on 2022-09-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('ked', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='cridt',
            new_name='credit',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='account_cridt',
        ),
        migrations.AddField(
            model_name='journal',
            name='account_credit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='account_credit', to='account.account'),
            preserve_default=False,
        ),
    ]
