# Generated by Django 3.2.8 on 2022-09-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('client', models.BooleanField(default=False)),
                ('supplier', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Customer_pics')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber1', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('tradeRecord', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('webSite', models.URLField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
