# Generated by Django 3.2.8 on 2022-07-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Customer_pics')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber1', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('phoneNumber3', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('phoneNumber4', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('tradeRecord', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('webSite', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
