# Generated by Django 3.2.8 on 2022-07-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
