# Generated by Django 3.2.8 on 2022-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='box',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='box',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
