# Generated by Django 3.2.8 on 2022-09-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20220911_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='memo',
        ),
    ]
