# Generated by Django 3.2.8 on 2022-07-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
