# Generated by Django 3.2.8 on 2022-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20220725_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
