# Generated by Django 3.2.8 on 2022-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateField()),
                ('issue_end', models.DateField()),
                ('national_number', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='passport_pics')),
                ('nationality', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=2)),
                ('issue_place', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
