# Generated by Django 3.2.8 on 2022-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Company_pics')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phoneNumber1', models.CharField(blank=True, max_length=25, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=25, null=True)),
                ('phoneNumber3', models.CharField(blank=True, max_length=25, null=True)),
                ('phoneNumber4', models.CharField(blank=True, max_length=25, null=True)),
                ('tradeRecord', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('webSite', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة ',
                'verbose_name_plural': 'الشركات',
            },
        ),
    ]
