# Generated by Django 3.2.8 on 2022-07-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('reservation_type', models.CharField(choices=[('1', 'طيران'), ('2', 'بري'), ('3', 'بحري'), ('4', 'تكسي'), ('5', 'شحن'), ('6', 'فيزا'), ('7', 'تامين صحي'), ('8', 'سمة دخول'), ('9', 'شهادة صحية)')], max_length=3)),
                ('Date', models.DateTimeField()),
                ('PNR', models.PositiveIntegerField()),
                ('pay_price', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Cancelled')], default=1, max_length=2)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priveat_no1', models.TextField()),
                ('priveat_no2', models.TextField()),
                ('pay_price', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
