# Generated by Django 3.2.8 on 2022-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='PNR',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
